version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

#------------------------------- GCP production level deployment : --------------------------------------------
#In the production level we are not creating postrsql in the container we are use gcp cloud sql